import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Masthead from '../components/masthead'
import AboutUs from '../components/about-us'
import Skills from '../components/skills'
import Works from '../components/works'
import TrustedBy from '../components/trusted-by'

const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Shiro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Masthead />
      <AboutUs />
      <Skills />
      <Works />
      <TrustedBy />
    </div>
  )
}

export default Home
